version: '3.8'

services:
  backend:
    build:
      context: ./todoAppBackend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todoAppDb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - db

  frontend:
    build:
      context: ./todo-app-frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:8081/api/v1/task

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: todoAppDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 