DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    task_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at DATE,
    description VARCHAR(255),
    due_date DATE,
    is_completed BOOLEAN,
    title VARCHAR(255)
);
